TRANSLATION = {
"recv_gp": "???",
'recv_ab_fuel_sol':'After burner fuel solenoid',
'recv_ab_air_sol':		'After burner air solenoid',
'recv_rc_pw':			'Pulse width modulation',
'recv_ab_mot_perc':		'Afterburner motor percentage',
'recv_yaw':			'yaw movement',
'recv_pitch':			'Pitch movement',
'recv_ldr_air_sol':		'lidar air solenoid',
'thm_ab':			'Thermocouple at afterburner',
'thm_eng':			'Thermocouple on engine',
'thm_pitch':			'thermocouple at pitch',
'thm_yaw':			'Thermocouple at Yaw',
'thm_pump_amb':		'Ambient thermocouple',
'fuel_pres':			'Fuel Pressure',
'sbus_rpm':			'Turbine rpm',
'sbus_egt':			'afterburner egt',
'ab_flow_meter':		'Afterburner flow meter',
'fuel_tank_sol':			'Fuel tank solenoid',
'fuel_lvl':			'Fuel tank level',
'curr_pitch':		'Current Pitch'	,
'curr_yaw':		'Current Yaw',
'err':			'error message',
'time_millis':			'Time in milliseconds',
'fver':				'Firmware version',
'abfsol':				'afterburner fuel solenoid',
'engthr':				'Engine throttle',
'abasol':			'Afterburner air solenoid',
'abthr':			'Afterburner throttle',
'ldrair':				'Lidar Air',
'pitch'		:		'Pitch',
'yaw'		:		'Yaw',
'rserr'		:		'Reset error comman',
'rad'		:		'Torch movement in radians',
'vel'		:		'articulation velocity?',
'gver'		:		'GUI version',
'wtr_flow'	:		'water flow rate (gallons per minute/hour?)',
'wtr_temp'	:		'water temperature',
'estop_press'	:		'if e stop is pressed',
'estop_active'	:		'if e stop is active',
'err'			:	'Error message',
'fver'			:	'version number',
'turb_sol'		:	'Turbine solenoid on/off',
'ab_sol'		:		'Afterburner solenoid on/off',
'clear_air_sol'	:		'clean air on/off',
'water_sol'		:'water solenoid on/off',
'compCont'		:	'???',
'blower'		:		'blower on/off',
'turbpump'		:	'turbine pump on/off',
'abpump'		:	'Afterburner pump on/off',
'gydstrt'		:		'hydraulic start on/off??',
'hydVfd'		:		'hydraulic VFD setting',
'coolstrt'		:	'Cooling on/off',
'wtrStrt'		:		'water started',
'wpatervfd'		:	'water VFD setting',
'rserr'			:	'Reset Errpr',
'gver'			:	'Gui Version',
'clamp_p'		:	'clamp pressure',
'jacking_fr_p'	:		'jacking forward pressure',
'jacking_rr_p'	:		'jacking reverse pressure',
'brake_p'		:	'brake pressure',
'mmanifold_p'	:		'manifold pressure',
'rail_wire'		:	'rail wire distance??',
'clamp_wire'	:		'clamp wire distance?',
'encoder'		:	'encoder status',
'encoder_vel'	:		'encoder velocity??',
'front_lim_sw'	:		'front limit switch contact',
'rear_lim_sw'	:		'rear limit switch contact',
'fver'			:	'firmware version',
'err'			:	'error message',
'brk_rls'		:		'break release command',
'clmp_rls'		:	'clamp release command',
'clmp_eng'		:	'clamp engage command',
'jk_rr'			:	'jacking reverse',
'jk_fw'			:	'jacking forward',
'rl_valve_volt'	:		'release valve voltage',
'rserr'			:	'Reset error',
'gver'			:	'gui version',
}

DEFAULT_CHECKS = ['ab_flow_meter', 'wtr_flow']